# Generated by Django 5.0.6 on 2026-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='credits_reset_date',
            field=models.DateTimeField(blank=True, help_text='When credits_used next rolls back to zero.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='credits_used',
            field=models.IntegerField(default=0, help_text='Characters generated in the current billing period.'),
        ),
        migrations.AddField(
            model_name='user',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('scale', 'Scale')], default='free', help_text='Subscription plan. Controls credit and voice-clone limits.', max_length=20),
        ),
    ]
