# Generated by Django 5.0.6 on 2026-09-14 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generate', 'Generate'), ('approve', 'Approve'), ('reject', 'Reject'), ('export', 'Export'), ('login', 'Login'), ('logout', 'Logout')], max_length=30)),
                ('prompt_id', models.UUIDField(blank=True, help_text='Null for login/logout entries', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('before_status', models.CharField(blank=True, max_length=20, null=True)),
                ('after_status', models.CharField(blank=True, max_length=20, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_auditlog',
                'ordering': ['-timestamp'],
            },
        ),
    ]
