# Generated by Django 5.0.6 on 2026-09-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('generate', 'Generate'), ('approve', 'Approve'), ('reject', 'Reject'), ('export', 'Export'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout')], max_length=30),
        ),
    ]
