# Generated by Django 5.0.6 on 2026-09-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('logout', 'Logout'), ('generate', 'Generate'), ('delete', 'Delete'), ('voice_upload', 'Voice upload'), ('voice_delete', 'Voice delete'), ('profile_update', 'Profile update'), ('credits_reset', 'Credits reset'), ('approve', 'Approve'), ('reject', 'Reject'), ('export', 'Export')], max_length=30),
        ),
    ]
