# Generated by Django 5.0.6 on 2026-09-10 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_label', models.CharField(help_text='Human-readable version label e.g. v1.0', max_length=20)),
                ('provider', models.CharField(help_text='TTS provider e.g. chatterbox', max_length=50)),
                ('model_variant', models.CharField(help_text='Model variant e.g. original or turbo', max_length=20)),
                ('reference_audio', models.CharField(help_text='Path to the reference WAV file used for zero-shot cloning', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Only one model version should be active at a time')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this model version', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_models_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voice Model Version',
                'verbose_name_plural': 'Voice Model Versions',
                'db_table': 'prompts_voicemodelversion',
                'ordering': ['-created_at'],
            },
        ),
    ]
