# Generated by Django 5.0.6 on 2026-09-14 06:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemodelversion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='voicemodelversion',
            name='model_variant',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voicemodelversion',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voicemodelversion',
            name='provider',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='voicemodelversion',
            name='reference_audio',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='voicemodelversion',
            name='version_label',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='VoicePrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Raw input text, max 500 characters')),
                ('text_processed', models.TextField(blank=True, help_text='Text after preprocessing rules applied', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('live', 'Live')], default='draft', max_length=20)),
                ('audio_url', models.TextField(blank=True, help_text='Pre-signed S3 URL, valid 1 hour', null=True)),
                ('audio_s3_key', models.CharField(blank=True, help_text='Internal S3 key — never exposed in API', max_length=500, null=True)),
                ('duration_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task UUID for status polling', max_length=255, null=True)),
                ('error_detail', models.TextField(blank=True, help_text='Set when status is failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts_created', to=settings.AUTH_USER_MODEL)),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts_exported', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts_rejected', to=settings.AUTH_USER_MODEL)),
                ('voice_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='prompts.voicemodelversion')),
            ],
            options={
                'verbose_name': 'Voice Prompt',
                'verbose_name_plural': 'Voice Prompts',
                'db_table': 'prompts_voiceprompt',
                'ordering': ['-created_at'],
            },
        ),
    ]
