# Generated by Django 5.0.6 on 2026-09-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0002_alter_voicemodelversion_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiceprompt',
            name='export_s3_key',
            field=models.CharField(blank=True, help_text='Internal S3 key of the exported 8 kHz IVR WAV — never exposed in API. Kept separate from audio_s3_key so exporting does not destroy the reference to the playback-quality master.', max_length=500, null=True),
        ),
    ]
