# Generated by Django 5.0.6 on 2026-09-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0005_link_existing_exports'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemodelversion',
            name='audio_s3_key',
            field=models.CharField(blank=True, help_text='S3 key of the uploaded reference audio (44.1kHz WAV)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='voicemodelversion',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text="Friendly name shown in the UI, e.g. 'Rachel (English)'", max_length=100),
        ),
        migrations.AddField(
            model_name='voicemodelversion',
            name='language',
            field=models.CharField(choices=[('english', 'English'), ('urdu', 'Urdu'), ('hindi', 'Hindi'), ('bilingual', 'Bilingual')], default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='voicemodelversion',
            name='reference_text',
            field=models.TextField(blank=True, help_text='Transcript of the reference audio; auto-transcribed by the worker if empty', null=True),
        ),
    ]
