# Generated by Django 5.0.6 on 2026-09-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0006_voicemodelversion_audio_s3_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicemodelversion',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voicemodelversion',
            name='error_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voicemodelversion',
            name='staging_s3_key',
            field=models.CharField(blank=True, help_text='S3 key of the raw upload before processing; kept for debugging a failed row', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='voicemodelversion',
            # Existing rows (uploaded before this async pipeline existed)
            # already have a usable reference clip, so they backfill as
            # 'ready' rather than the model's real go-forward default of
            # 'processing' — preserve_default=False keeps that a one-time
            # historical value instead of the field's actual default.
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', help_text='Async processing state: convert -> trim -> transcribe -> ready', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voicemodelversion',
            name='reference_audio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='voicemodelversion',
            name='reference_text',
            field=models.TextField(blank=True, help_text='Transcript of the reference audio. English voices are auto-transcribed by the worker if left empty at upload; other languages require a manually-typed Roman-script transcript.', null=True),
        ),
    ]
