# Generated by Django 5.0.6 on 2026-09-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0007_voicemodelversion_processing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicemodelversion',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='processing', help_text='Async processing state: convert -> trim -> transcribe -> ready', max_length=20),
        ),
    ]
