# Generated by Django 5.0.6 on 2026-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompts', '0008_alter_voicemodelversion_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voicemodelversion',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'Voice Model Version', 'verbose_name_plural': 'Voice Model Versions'},
        ),
        migrations.AlterModelOptions(
            name='voiceprompt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Generation', 'verbose_name_plural': 'Generations'},
        ),
        migrations.AddField(
            model_name='voicemodelversion',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Platform-provided voice: visible to every account, cannot be deleted, and never counts toward a user's voice-clone limit."),
        ),
        migrations.AddField(
            model_name='voiceprompt',
            name='credits_charged',
            field=models.IntegerField(default=0, help_text='Credits deducted for this generation (1 credit per character).'),
        ),
        migrations.AddField(
            model_name='voiceprompt',
            name='mp3_s3_key',
            field=models.CharField(blank=True, help_text='Internal S3 key of the MP3 transcode, created lazily on first MP3 download.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='voiceprompt',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='voiceprompt',
            name='text',
            field=models.TextField(help_text='Raw input text, max 5000 characters'),
        ),
    ]
